name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # Ensure all commands run in the repository root

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the application with environment variables
      - name: Build application
        run: npm run build
        env:
          VITE_ENV: ${{ secrets.VITE_ENV }}
          VITE_APPSYNC_URL: ${{ secrets.VITE_APPSYNC_URL }}
          VITE_APPSYNC_API_KEY: ${{ secrets.VITE_APPSYNC_API_KEY }}
          VITE_APPSYNC_REGION: ${{ secrets.VITE_APPSYNC_REGION }}

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Set up AWS CLI credentials file
      - name: Set up AWS CLI credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = ap-southeast-2" >> ~/.aws/config

      # Debug environment
      - name: Debug environment
        run: |
          pwd
          ls -la
          ls -la dist/
          aws sts get-caller-identity
          aws amplify list-apps --query "apps[?appId=='${{ secrets.AMPLIFY_APP_ID }}']"
          aws amplify list-branches --app-id ${{ secrets.AMPLIFY_APP_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Upload files to S3 deployment bucket
      - name: Upload to S3
        run: aws s3 cp dist/ s3://amplify-frontend-dev-505cc-deployment/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Invalidate CloudFront distribution
      - name: Invalidate CloudFront
        run: |
          DISTRIBUTION_ID=$(aws amplify list-branches --app-id ${{ secrets.AMPLIFY_APP_ID }} --query "branches[?branchName=='dev'].distributionId" --output text)
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Error: Could not retrieve distribution ID. Please set DISTRIBUTION_ID secret."
            exit 1
          fi
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
