name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # Ensure all commands run in the repository root

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the application with environment variables
      - name: Build application
        run: npm run build
        env:
          VITE_ENV: ${{ secrets.VITE_ENV }}
          VITE_APPSYNC_URL: ${{ secrets.VITE_APPSYNC_URL }}
          VITE_APPSYNC_API_KEY: ${{ secrets.VITE_APPSYNC_API_KEY }}
          VITE_APPSYNC_REGION: ${{ secrets.VITE_APPSYNC_REGION }}

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Install AWS Amplify CLI
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      # Debug environment (before Amplify commands)
      - name: Debug environment
        run: |
          pwd
          ls -la
          ls -la dist/ || echo "dist/ directory not found"
          ls -la amplify/ || echo "amplify/ directory not found"
          amplify env list || echo "Failed to list environments"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Initialize Amplify environment
      - name: Initialize Amplify environment
        run: amplify init --appId d2qv7o8zflnrg7 --envName dev --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Select Amplify environment
      - name: Select Amplify environment
        run: amplify env checkout dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Verify Amplify status
      - name: Verify Amplify status
        run: amplify status --env-name dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      # Deploy to AWS Amplify
      - name: Deploy to Amplify
        run: amplify publish --yes --env-name dev --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
